# -*- coding: utf-8 -*-
"""25 wikis の定義。platform: mw / atwiki / seesaa / wikiwiki / wiki3 / memo / fc2"""
WIKIS = [
    {"key": "hikamers",            "label": "ヒカマーwiki (hikamers.net)", "platform": "mw",     "api": "https://hikamers.net/api.php",             "site": "https://hikamers.net/wiki/",            "pow": True},
    {"key": "atw_hikamer",         "label": "ヒカマーwiki (atwiki)",        "platform": "atwiki",  "site": "https://w.atwiki.jp/hikamer/"},
    {"key": "atw_hikamerswiki6",   "label": "ヒカマーwiki6",                "platform": "atwiki",  "site": "https://w.atwiki.jp/hikamerswiki6/"},
    {"key": "seesaa_hikakinmania", "label": "Hikakin_Mania Wiki (seesaa)",  "platform": "seesaa",  "site": "https://seesaawiki.jp/hikakinmania/"},
    {"key": "seesaa_hikakin_mania","label": "Hikakin_Mania Wiki (seesaa2)", "platform": "seesaa",  "site": "https://seesaawiki.jp/hikakin_mania/"},
    {"key": "atw_hikasei_mania",   "label": "hikasei_mania",                "platform": "atwiki",  "site": "https://w.atwiki.jp/hikasei_mania/"},
    {"key": "ww_huromani",         "label": "Hikamer Wiki (wikiwiki)",      "platform": "wikiwiki", "site": "https://wikiwiki.jp/huromani/"},
    {"key": "ww_hika_mer53",       "label": "ヒカマーwiki (wikiwiki)",      "platform": "wikiwiki", "site": "https://wikiwiki.jp/hika-mer53/"},
    {"key": "fandom_hikakin",      "label": "HIKAKIN Wiki (Fandom)",        "platform": "mw",     "api": "https://hikakin.fandom.com/ja/api.php",  "site": "https://hikakin.fandom.com/ja/"},
    {"key": "wiki3_hikamani",      "label": "Re:Hikakin_mania創作wiki",     "platform": "wiki3",   "site": "https://wiki3.jp/hikamani/"},
    {"key": "memo_hikakinmania",   "label": "hikakin-mania (memo.wiki)",    "platform": "memo",    "site": "https://hikakin-mania.memo.wiki/"},
    {"key": "fandom_tsuihaikaiwai","label": "ツイ廃界隈 Wiki (Fandom)",      "platform": "mw",     "api": "https://tsuihaikaiwai.fandom.com/ja/api.php", "site": "https://tsuihaikaiwai.fandom.com/ja/"},
    {"key": "ww_sfxxtdz66",        "label": "m / ヒカマーwiki (wikiwiki)",  "platform": "wikiwiki", "site": "https://wikiwiki.jp/sfxxtdz66/"},
    {"key": "inmu",                "label": "淫ク☆解説Wiki",                "platform": "mw",     "api": "https://inmu-cookie-wiki.org/api.php",     "site": "https://inmu-cookie-wiki.org/wiki/",       "delay": 1.2},
    {"key": "ww_noire",            "label": "Xのヒカマニ界隈(ヒカマー) Wiki", "platform": "wikiwiki", "site": "https://wikiwiki.jp/noire/"},
    {"key": "memo_gaymasuo",       "label": "gaymasuo (memo.wiki)",         "platform": "memo",    "site": "https://gaymasuo.memo.wiki/"},
    {"key": "atw_twihigh_tcg",     "label": "ツイ廃TCG",                     "platform": "atwiki",  "site": "https://w.atwiki.jp/twihigh_tcg/"},
    {"key": "atw_tsuihaikaiwai",   "label": "ツイ廃界隈 @Wiki",              "platform": "atwiki",  "site": "https://w.atwiki.jp/tsuihaikaiwai/"},
    {"key": "reinoare",            "label": "例のアレ辞典",                  "platform": "mw",     "api": "https://wiki.reinoare.com/w/api.php",     "site": "https://wiki.reinoare.com/wiki/"},
    {"key": "krsw",                "label": "唐澤貴洋Wiki",                  "platform": "mw",     "api": "https://krsw-wiki.in/api.php",            "site": "https://krsw-wiki.in/wiki/"},
    {"key": "fandom_otomad",       "label": "音MAD Wiki (Fandom)",          "platform": "mw",     "api": "https://otomad.fandom.com/ja/api.php",   "site": "https://otomad.fandom.com/ja/"},
    {"key": "fc2_youtuber",        "label": "YouTuberWiki (fc2)",           "platform": "fc2",     "site": "https://youtuber.wiki.fc2.com/"},
    {"key": "fc2_horrorinm",       "label": "ホラー・ミステリー淫夢Wiki",    "platform": "fc2",     "site": "https://horrorinm.wiki.fc2.com/"},
    {"key": "yjsnpi",              "label": "真夏の夜の淫夢Wiki",            "platform": "mw",     "api": "https://wiki.yjsnpi.nu/w/api.php",        "site": "https://wiki.yjsnpi.nu/wiki/"},
    {"key": "atw_cookie_kaisetu",  "label": "クッキー☆解説Wiki",            "platform": "atwiki",  "site": "https://w.atwiki.jp/cookie_kaisetu/"},
]
